title: Unity Utilities for Game Dev
description: Class projects and test for game dev
theme: just-the-docs

url: https://MartaGnarta.github.io/UnityUtilities

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/MartaGnarta/UnityUtilities
